# Generated by Django 5.2.7 on 2025-10-21 18:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto Base',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlmacenamientoHDD',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('capacidad_gb', models.IntegerField()),
                ('velocidad_rpm', models.IntegerField(verbose_name='Velocidad (RPM)')),
                ('cache_mb', models.IntegerField(verbose_name='Cache (MB)')),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='AlmacenamientoSSD',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('capacidad_gb', models.IntegerField()),
                ('interfaz', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=10)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='FuenteDePoder',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('potencia_watts', models.IntegerField(verbose_name='Potencia (W)')),
                ('certificacion', models.CharField(max_length=20)),
                ('modular', models.BooleanField(default=False)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('formato_soporte', models.CharField(max_length=50, verbose_name='Soporte Placa')),
                ('ventiladores_incluidos', models.IntegerField()),
                ('material', models.CharField(max_length=50)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('capacidad_gb', models.IntegerField()),
                ('tipo_ddr', models.CharField(max_length=5)),
                ('velocidad_mhz', models.IntegerField()),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('socket_cpu', models.CharField(max_length=20)),
                ('chipset', models.CharField(max_length=30)),
                ('formato', models.CharField(max_length=30)),
                ('ranuras_ram', models.IntegerField(verbose_name='Slots RAM')),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('socket', models.CharField(max_length=20)),
                ('nucleos', models.IntegerField()),
                ('frecuencia_base', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='RefrigeracionCooler',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('tipo', models.CharField(max_length=20)),
                ('socket_compatibles', models.CharField(max_length=150)),
                ('tamanho_radiador_mm', models.IntegerField(blank=True, null=True)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='TarjetaGrafica',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('vram_gb', models.IntegerField()),
                ('tipo_memoria', models.CharField(max_length=10)),
                ('interfaz', models.CharField(max_length=20)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='Ventilador',
            fields=[
                ('productobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.productobase')),
                ('tamanho_mm', models.IntegerField(verbose_name='Tamaño (mm)')),
                ('velocidad_rpm', models.IntegerField(verbose_name='Velocidad (RPM)')),
                ('rgb', models.BooleanField(default=False)),
            ],
            bases=('core.productobase',),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productobase',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('calificacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.productobase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productobase')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pago Confirmado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('comuna_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('transaccion_id', models.CharField(max_length=100, unique=True)),
                ('nombre_comprador', models.CharField(max_length=200)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_boleta', to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='core.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='core.region'),
        ),
    ]
