# Generated by Django 4.2.25 on 2025-11-03 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenamientoHDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Disco Duro HDD', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('capacidad_gb', models.IntegerField(verbose_name='Capacidad (GB)')),
                ('velocidad_rpm', models.IntegerField(verbose_name='Velocidad (RPM)')),
                ('cache_mb', models.IntegerField(verbose_name='Cache (MB)')),
            ],
            options={
                'verbose_name_plural': 'Almacenamiento HDD',
            },
        ),
        migrations.CreateModel(
            name='AlmacenamientoSSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='SSD', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('capacidad_gb', models.IntegerField(verbose_name='Capacidad (GB)')),
                ('interfaz', models.CharField(max_length=20)),
                ('formato', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Almacenamiento SSD',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuenteDePoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Fuente de Poder', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('potencia_watts', models.IntegerField(verbose_name='Potencia (W)')),
                ('certificacion', models.CharField(max_length=20)),
                ('modular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fuentes de Poder (PSU)',
            },
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Gabinete', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('formato_soporte', models.CharField(max_length=50, verbose_name='Soporte Placa')),
                ('ventiladores_incluidos', models.BooleanField(default=False)),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Gabinetes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='proveedores/')),
            ],
            options={
                'verbose_name_plural': 'Proveedores / Marcas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ventilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Ventilador', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('tamanho_mm', models.IntegerField(verbose_name='Tamaño (mm)')),
                ('velocidad_rpm', models.IntegerField(verbose_name='Velocidad (RPM)')),
                ('rgb', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Ventiladores',
            },
        ),
        migrations.CreateModel(
            name='TarjetaGrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Tarjeta Gráfica', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('vram_gb', models.IntegerField(verbose_name='VRAM (GB)')),
                ('tipo_memoria', models.CharField(max_length=10, verbose_name='Tipo Memoria')),
                ('interfaz', models.CharField(max_length=20, verbose_name='Interfaz Bus')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Tarjetas Gráficas (GPU)',
            },
        ),
        migrations.CreateModel(
            name='RefrigeracionCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Refrigeración', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo (Aire/Líquida)')),
                ('socket_compatibles', models.CharField(max_length=150, verbose_name='Sockets Comp.')),
                ('tamanho_radiador_mm', models.IntegerField(blank=True, null=True, verbose_name='Radiador (mm)')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Refrigeración (Cooler)',
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='CPU', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('socket', models.CharField(max_length=20)),
                ('nucleos', models.IntegerField()),
                ('frecuencia_base', models.DecimalField(decimal_places=2, max_digits=4)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Procesadores (CPU)',
            },
        ),
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Placa Madre', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('socket_cpu', models.CharField(max_length=20, verbose_name='Socket CPU')),
                ('chipset', models.CharField(max_length=30)),
                ('formato', models.CharField(max_length=30)),
                ('ranuras_ram', models.IntegerField(verbose_name='Slots RAM')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Placas Madre',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pago Confirmado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('comuna_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('transaccion_id', models.CharField(max_length=100, unique=True)),
                ('nombre_comprador', models.CharField(max_length=200)),
                ('email_comprador', models.EmailField(max_length=254)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_boleta', to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Memoria RAM', editable=False, max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('capacidad_gb', models.IntegerField(verbose_name='Capacidad (GB)')),
                ('tipo_ddr', models.CharField(max_length=5, verbose_name='Tipo DDR')),
                ('velocidad_mhz', models.IntegerField(verbose_name='Velocidad (MHz)')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Memorias RAM',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200, verbose_name='Producto')),
                ('producto_tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('almacenamiento_hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.almacenamientohdd')),
                ('almacenamiento_ssd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.almacenamientossd')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.carrito')),
                ('fuente_de_poder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fuentedepoder')),
                ('gabinete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gabinete')),
                ('memoria_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.memoriaram')),
                ('placa_madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.placamadre')),
                ('procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.procesador')),
                ('refrigeracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.refrigeracioncooler')),
                ('tarjeta_grafica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarjetagrafica')),
                ('ventilador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventilador')),
            ],
        ),
        migrations.AddField(
            model_name='gabinete',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor'),
        ),
        migrations.AddField(
            model_name='fuentedepoder',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='core.region'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('calificacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('almacenamiento_hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.almacenamientohdd')),
                ('almacenamiento_ssd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.almacenamientossd')),
                ('fuente_de_poder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fuentedepoder')),
                ('gabinete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gabinete')),
                ('memoria_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.memoriaram')),
                ('placa_madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.placamadre')),
                ('procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.procesador')),
                ('refrigeracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.refrigeracioncooler')),
                ('tarjeta_grafica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarjetagrafica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ventilador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventilador')),
            ],
        ),
        migrations.AddField(
            model_name='almacenamientossd',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor'),
        ),
        migrations.AddField(
            model_name='almacenamientohdd',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor', verbose_name='Marca/Proveedor'),
        ),
    ]
