# Generated by Django 4.2.25 on 2025-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='almacenamientohdd',
            name='capacidad_gb',
            field=models.IntegerField(verbose_name='Capacidad (GB)'),
        ),
        migrations.AlterField(
            model_name='almacenamientossd',
            name='capacidad_gb',
            field=models.IntegerField(verbose_name='Capacidad (GB)'),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='capacidad_gb',
            field=models.IntegerField(verbose_name='Capacidad (GB)'),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='tipo_ddr',
            field=models.CharField(max_length=5, verbose_name='Tipo DDR'),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='velocidad_mhz',
            field=models.IntegerField(verbose_name='Velocidad (MHz)'),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='socket_cpu',
            field=models.CharField(max_length=20, verbose_name='Socket CPU'),
        ),
        migrations.AlterField(
            model_name='refrigeracioncooler',
            name='socket_compatibles',
            field=models.CharField(max_length=150, verbose_name='Sockets Comp.'),
        ),
        migrations.AlterField(
            model_name='refrigeracioncooler',
            name='tamanho_radiador_mm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiador (mm)'),
        ),
        migrations.AlterField(
            model_name='refrigeracioncooler',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo (Aire/Líquida)'),
        ),
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='interfaz',
            field=models.CharField(max_length=20, verbose_name='Interfaz Bus'),
        ),
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='tipo_memoria',
            field=models.CharField(max_length=10, verbose_name='Tipo Memoria'),
        ),
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='vram_gb',
            field=models.IntegerField(verbose_name='VRAM (GB)'),
        ),
    ]
