# Generated by Django 4.2.25 on 2025-11-05 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('almacenamiento_hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.almacenamientohdd')),
                ('almacenamiento_ssd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.almacenamientossd')),
                ('fuente_de_poder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fuentedepoder')),
                ('gabinete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gabinete')),
                ('memoria_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.memoriaram')),
                ('placa_madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.placamadre')),
                ('procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.procesador')),
                ('refrigeracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.refrigeracioncooler')),
                ('tarjeta_grafica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarjetagrafica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('ventilador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventilador')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'procesador'), name='unique_fav_procesador'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'tarjeta_grafica'), name='unique_fav_tarjeta_grafica'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'memoria_ram'), name='unique_fav_memoria_ram'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'placa_madre'), name='unique_fav_placa_madre'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'almacenamiento_ssd'), name='unique_fav_almacenamiento_ssd'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'almacenamiento_hdd'), name='unique_fav_almacenamiento_hdd'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'gabinete'), name='unique_fav_gabinete'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'fuente_de_poder'), name='unique_fav_fuente_de_poder'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'refrigeracion'), name='unique_fav_refrigeracion'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('usuario', 'ventilador'), name='unique_fav_ventilador'),
        ),
    ]
