# Generated by Django 4.2.25 on 2025-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favorito_favorito_unique_fav_procesador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placamadre',
            name='tipo_ram_soportado',
            field=models.CharField(default='DDR4', max_length=10, verbose_name='Tipo RAM Soportado'),
        ),
    ]
