# Generated by Django 4.2.25 on 2025-11-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_placamadre_tipo_ram_soportado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenamientohdd',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='almacenamientossd',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='almacenamientossd',
            name='formato',
            field=models.CharField(choices=[('M.2 2280', 'M.2 2280'), ('2.5"', '2.5"')], max_length=10),
        ),
        migrations.AlterField(
            model_name='almacenamientossd',
            name='interfaz',
            field=models.CharField(choices=[('NVMe PCIe 4.0', 'NVMe PCIe 4.0'), ('NVMe PCIe 3.0', 'NVMe PCIe 3.0'), ('SATA III', 'SATA III')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuentedepoder',
            name='certificacion',
            field=models.CharField(choices=[('80+ White', '80+ White'), ('80+ Bronze', '80+ Bronze'), ('80+ Silver', '80+ Silver'), ('80+ Gold', '80+ Gold'), ('80+ Platinum', '80+ Platinum'), ('80+ Titanium', '80+ Titanium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuentedepoder',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='formato_soporte',
            field=models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=50, verbose_name='Soporte Placa'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='material',
            field=models.CharField(choices=[('Acero', 'Acero'), ('Aluminio', 'Aluminio'), ('Plástico', 'Plástico'), ('Vidrio Templado', 'Vidrio Templado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='tipo_ddr',
            field=models.CharField(choices=[('DDR5', 'DDR5'), ('DDR4', 'DDR4'), ('DDR3', 'DDR3')], max_length=5, verbose_name='Tipo DDR'),
        ),
        migrations.AlterField(
            model_name='memoriaram',
            name='velocidad_mhz',
            field=models.IntegerField(help_text='Ej: 3200, 5600', verbose_name='Velocidad (MHz)'),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='chipset',
            field=models.CharField(choices=[('B550', 'B550'), ('B650', 'B650'), ('Z790', 'Z790'), ('X670', 'X670'), ('Otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='formato',
            field=models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=30),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='socket_cpu',
            field=models.CharField(choices=[('AM4', 'AM4'), ('AM5', 'AM5'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('Otro', 'Otro')], max_length=20, verbose_name='Socket CPU'),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='tipo_ram_soportado',
            field=models.CharField(choices=[('DDR5', 'DDR5'), ('DDR4', 'DDR4'), ('DDR3', 'DDR3')], default='DDR4', max_length=10, verbose_name='Tipo RAM Soportado'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='frecuencia_base',
            field=models.DecimalField(decimal_places=2, help_text='En GHz. Ej: 3.70', max_digits=4),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='socket',
            field=models.CharField(choices=[('AM4', 'AM4'), ('AM5', 'AM5'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('Otro', 'Otro (Especificar)')], help_text='Socket del procesador', max_length=20),
        ),
        migrations.AlterField(
            model_name='refrigeracioncooler',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refrigeracioncooler',
            name='socket_compatibles',
            field=models.CharField(help_text='Separar por comas. Ej: AM4, AM5, LGA1700', max_length=150, verbose_name='Sockets Comp.'),
        ),
        migrations.AlterField(
            model_name='refrigeracioncooler',
            name='tipo',
            field=models.CharField(choices=[('Aire', 'Aire'), ('Líquida', 'Líquida (AIO)')], max_length=20, verbose_name='Tipo (Aire/Líquida)'),
        ),
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='interfaz',
            field=models.CharField(choices=[('PCIe 4.0', 'PCIe 4.0'), ('PCIe 5.0', 'PCIe 5.0'), ('PCIe 3.0', 'PCIe 3.0'), ('Otro', 'Otro')], max_length=20, verbose_name='Interfaz Bus'),
        ),
        migrations.AlterField(
            model_name='tarjetagrafica',
            name='tipo_memoria',
            field=models.CharField(choices=[('GDDR6X', 'GDDR6X'), ('GDDR6', 'GDDR6'), ('GDDR5', 'GDDR5'), ('Otro', 'Otro')], max_length=10, verbose_name='Tipo Memoria'),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
