# Generated by Django 4.2.25 on 2025-11-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_almacenamientohdd_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='paypal_transaccion_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción PayPal'),
        ),
    ]
