"""
Django settings for HardWareHouse project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('true', '1', 'yes')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('Falta la variable SECRET_KEY. Defínela en el archivo .env (ver .env.example).')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)

# Reemplaza 'url-ejemplo' por el dominio o la IP pública que te entregue AWS, sin 'https://'.
# Ejemplo: 'ec2-3-90-12-34.compute-1.amazonaws.com' o 'www.hardwarehouse.cl'
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '8w96bzrx-8000.brs.devtunnels.ms', 'url-ejemplo']

# Mismo dominio que en ALLOWED_HOSTS, pero aquí con el esquema 'https://'.
CSRF_TRUSTED_ORIGINS = ['https://8w96bzrx-8000.brs.devtunnels.ms', 'https://url-ejemplo']

# Requiere que el sitio se sirva por HTTPS (Nginx debe enviar la cabecera X-Forwarded-Proto).
# Si en AWS todavía accedes por http://, define USE_HTTPS=False en el .env o no podrás iniciar sesión.
USE_HTTPS = env_bool('USE_HTTPS', default=not DEBUG)
if USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'bootstrap5',
    'django.contrib.humanize',
    'paypal.standard.ipn',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HardWareHouse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.extras_context', # Añadido para contadores globales
            ],
        },
    },
]

WSGI_APPLICATION = 'HardWareHouse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "bd_hardwarehouse"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl' 

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde 'python manage.py collectstatic' reúne los estáticos para que Nginx los sirva.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ruta absoluta al directorio donde Django almacenará los archivos subidos por el usuario (imágenes de productos).
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL pública que se utilizará para acceder a los archivos multimedia.
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/'  
LOGOUT_REDIRECT_URL = '/'  
LOGIN_URL = '/login/' 

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ----------------------------------------------------
# CONFIGURACIÓN DEL PANEL DE ADMINISTRACIÓN
# ----------------------------------------------------

ADMIN_SITE_TITLE = 'Panel de Administración HardWareHouse' 

ADMIN_HEADER_TITLE = 'Administración de la Tienda' 

ADMIN_SITE_HEADER = 'HardWareHouse'

PAYPAL_RECEIVER_EMAIL = 'sb-j1cpn47385379@business.example.com'
PAYPAL_TEST = True

# Tasa de cambio de ejemplo (CLP a USD). En un proyecto real, esto debería obtenerse de una API.
CLP_TO_USD_RATE = 950 

# URL base pública del sitio, sin '/' final. PayPal la usa para el IPN y las redirecciones.
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000').rstrip('/')

# ----------------------------------------------------
# CONFIGURACIÓN DE LOGGING
# ----------------------------------------------------

# Creamos el directorio de logs si no existe para evitar errores al iniciar.
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'paypal_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'paypal_ipn.log'),
            'maxBytes': 1024 * 1024 * 5,  
            'backupCount': 2,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'paypal.ipn': {
            'handlers': ['console', 'paypal_file'],
            'level': 'INFO',
            'propagate': False, 
        },
    },
}
